dist: xenial
language: python
python:
- 3.6
- 3.7
before_install:
- pip install -U pip setuptools
install:
- pip install .[dev]
script:
- black --check .
- flake8 .
- pytest tests
deploy:
  provider: pypi
  user: tamr
  password:
    secure: hYdrqOlN4Y7Vb+dr6/Z5tSv38ky8HjW7Bc+WTIIrpZ0JtzlJ5qfg81l9hWtWVOXhKRmtEM45xYp3meTTwKIlntbP4U0TkAq1GJFGd78G4CgypGvuxXSysVaRnuvZU90RFO62xzHTSfRg0aiMokqlHQV96mGEBFbTQ/jLr+y4OpR5ilJc6VuX/ZXbQWdCiLBlvifAYrpPxKy+tjv4Z80afkAQLkQ23HH/tvcN+7hdn/ilSZIiSnPavRT8gm54BwxhRCixxsfWhcJ/jrQsdbScKS9QL69S18WZDyb1G3zuuHDIyb+sCmseMRaOiVF5rjgG3ckNIo9TAnqfCh0dXNYNTJ3fAUW7FuzNjS5waH7gkStupOVPDdR3JdYYj7/JeFLAdQWpEY7+HVj28WULQt4LIo1UOCHGlN0PGcWlmjM9kS9YGgue37BftjHKHhDb/3Dojqv8Bkn43g7gKg4acn6XSew5b1BP+w2JjvLIc1lbMX4fJYJA+X4nByiVmnx+pP75NwV+qSfFLJC+4+zs97yNMS01PXfGfKHdn7QX230bk+YFoPl+rkVjWE8nsM54IhejsfvaeBiCsIFyrYebGe3ME8Ur4yqFddrk8F7aJDJMIbFffgvj5srCNOknlNtiOIqZcqzSQcc9myDVq8uXHZIFapsNHtcwGbVkvLIt3FdjOhI=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
